# Generated by Django 2.0.7 on 2018-07-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_questioncreate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionCreate',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='option5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='qn',
            field=models.TextField(default=''),
        ),
    ]
